using System.CodeDom.Compiler;
using Android.Runtime;


#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ResourceDesigner("ScratchingPost.Droid.Resource", IsApplication=true)]

namespace ScratchingPost.Droid
{
	
	
	[GeneratedCode("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Acr.Support.Android.Resource.String.ApplicationName = String.ApplicationName;
			Acr.Support.Android.Resource.String.Hello = String.Hello;
			AndroidHUD.Resource.Attribute.ahBarColor = Attribute.ahBarColor;
			AndroidHUD.Resource.Attribute.ahBarLength = Attribute.ahBarLength;
			AndroidHUD.Resource.Attribute.ahBarWidth = Attribute.ahBarWidth;
			AndroidHUD.Resource.Attribute.ahCircleColor = Attribute.ahCircleColor;
			AndroidHUD.Resource.Attribute.ahDelayMillis = Attribute.ahDelayMillis;
			AndroidHUD.Resource.Attribute.ahRadius = Attribute.ahRadius;
			AndroidHUD.Resource.Attribute.ahRimColor = Attribute.ahRimColor;
			AndroidHUD.Resource.Attribute.ahRimWidth = Attribute.ahRimWidth;
			AndroidHUD.Resource.Attribute.ahSpinSpeed = Attribute.ahSpinSpeed;
			AndroidHUD.Resource.Attribute.ahText = Attribute.ahText;
			AndroidHUD.Resource.Attribute.ahTextColor = Attribute.ahTextColor;
			AndroidHUD.Resource.Attribute.ahTextSize = Attribute.ahTextSize;
			AndroidHUD.Resource.Drawable.ic_errorstatus = Drawable.ic_errorstatus;
			AndroidHUD.Resource.Drawable.ic_successstatus = Drawable.ic_successstatus;
			AndroidHUD.Resource.Drawable.roundedbg = Drawable.roundedbg;
			AndroidHUD.Resource.Drawable.roundedbgdark = Drawable.roundedbgdark;
			AndroidHUD.Resource.Id.loadingImage = Id.loadingImage;
			AndroidHUD.Resource.Id.loadingProgressBar = Id.loadingProgressBar;
			AndroidHUD.Resource.Id.loadingProgressWheel = Id.loadingProgressWheel;
			AndroidHUD.Resource.Id.textViewStatus = Id.textViewStatus;
			AndroidHUD.Resource.Layout.loading = Layout.loading;
			AndroidHUD.Resource.Layout.loadingimage = Layout.loadingimage;
			AndroidHUD.Resource.Layout.loadingprogress = Layout.loadingprogress;
			AndroidHUD.Resource.String.library_name = String.library_name;
			AndroidHUD.Resource.Styleable.ProgressWheel = Styleable.ProgressWheel;
			AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = Styleable.ProgressWheel_ahBarColor;
			AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = Styleable.ProgressWheel_ahBarLength;
			AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = Styleable.ProgressWheel_ahBarWidth;
			AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = Styleable.ProgressWheel_ahCircleColor;
			AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = Styleable.ProgressWheel_ahDelayMillis;
			AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = Styleable.ProgressWheel_ahRadius;
			AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = Styleable.ProgressWheel_ahRimColor;
			AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = Styleable.ProgressWheel_ahRimWidth;
			AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = Styleable.ProgressWheel_ahSpinSpeed;
			AndroidHUD.Resource.Styleable.ProgressWheel_ahText = Styleable.ProgressWheel_ahText;
			AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = Styleable.ProgressWheel_ahTextColor;
			AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = Styleable.ProgressWheel_ahTextSize;
			Splat.Resource.String.library_name = String.library_name;
			Xamarin.Forms.Platform.Resource.String.ApplicationName = String.ApplicationName;
			Xamarin.Forms.Platform.Resource.String.Hello = String.Hello;
			XLabs.Forms.Resource.Color.calendar_active_month_bg = Color.calendar_active_month_bg;
			XLabs.Forms.Resource.Color.calendar_bg = Color.calendar_bg;
			XLabs.Forms.Resource.Color.calendar_divider = Color.calendar_divider;
			XLabs.Forms.Resource.Color.calendar_highlighted_day_bg = Color.calendar_highlighted_day_bg;
			XLabs.Forms.Resource.Color.calendar_inactive_month_bg = Color.calendar_inactive_month_bg;
			XLabs.Forms.Resource.Color.calendar_selected_day_bg = Color.calendar_selected_day_bg;
			XLabs.Forms.Resource.Color.calendar_selected_range_bg = Color.calendar_selected_range_bg;
			XLabs.Forms.Resource.Color.calendar_text_active = Color.calendar_text_active;
			XLabs.Forms.Resource.Color.calendar_text_inactive = Color.calendar_text_inactive;
			XLabs.Forms.Resource.Color.calendar_text_selected = Color.calendar_text_selected;
			XLabs.Forms.Resource.Color.calendar_text_selector = Color.calendar_text_selector;
			XLabs.Forms.Resource.Color.calendar_text_unselectable = Color.calendar_text_unselectable;
			XLabs.Forms.Resource.Dimension.calendar_day_headers_paddingbottom = Dimension.calendar_day_headers_paddingbottom;
			XLabs.Forms.Resource.Dimension.calendar_month_title_bottommargin = Dimension.calendar_month_title_bottommargin;
			XLabs.Forms.Resource.Dimension.calendar_month_topmargin = Dimension.calendar_month_topmargin;
			XLabs.Forms.Resource.Dimension.calendar_text_medium = Dimension.calendar_text_medium;
			XLabs.Forms.Resource.Dimension.calendar_text_small = Dimension.calendar_text_small;
			XLabs.Forms.Resource.Drawable.ad16 = Drawable.ad16;
			XLabs.Forms.Resource.Drawable.calendar_bg_selector = Drawable.calendar_bg_selector;
			XLabs.Forms.Resource.Id.calendar_grid = Id.calendar_grid;
			XLabs.Forms.Resource.Id.calendar_view = Id.calendar_view;
			XLabs.Forms.Resource.Id.left_arrow = Id.left_arrow;
			XLabs.Forms.Resource.Id.right_arrow = Id.right_arrow;
			XLabs.Forms.Resource.Id.title = Id.title;
			XLabs.Forms.Resource.Layout.calendar_pager_layout = Layout.calendar_pager_layout;
			XLabs.Forms.Resource.Layout.calendar_picker = Layout.calendar_picker;
			XLabs.Forms.Resource.Layout.dialog = Layout.dialog;
			XLabs.Forms.Resource.Layout.month = Layout.month;
			XLabs.Forms.Resource.Layout.week = Layout.week;
			XLabs.Forms.Resource.String.ApplicationName = String.ApplicationName;
			XLabs.Forms.Resource.String.Hello = String.Hello;
			XLabs.Forms.Resource.String.day_name_format = String.day_name_format;
			XLabs.Forms.Resource.String.full_date_format = String.full_date_format;
			XLabs.Forms.Resource.String.invalid_date = String.invalid_date;
			XLabs.Forms.Resource.String.library_name = String.library_name;
			XLabs.Forms.Resource.String.month_name_format = String.month_name_format;
			XLabs.Forms.Resource.Style.CalendarCell = Style.CalendarCell;
			XLabs.Forms.Resource.Style.CalendarCell_CalendarDate = Style.CalendarCell_CalendarDate;
			XLabs.Forms.Resource.Style.CalendarCell_DayHeader = Style.CalendarCell_DayHeader;
			XLabs.Forms.Resource.Style.CalendarTitle = Style.CalendarTitle;
			XLabs.Platform.Resource.String.ApplicationName = String.ApplicationName;
			XLabs.Platform.Resource.String.Hello = String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010016
			public const int ahBarColor = 2130771990;
			
			// aapt resource value: 0x7f01001e
			public const int ahBarLength = 2130771998;
			
			// aapt resource value: 0x7f01001d
			public const int ahBarWidth = 2130771997;
			
			// aapt resource value: 0x7f01001b
			public const int ahCircleColor = 2130771995;
			
			// aapt resource value: 0x7f01001a
			public const int ahDelayMillis = 2130771994;
			
			// aapt resource value: 0x7f01001c
			public const int ahRadius = 2130771996;
			
			// aapt resource value: 0x7f010017
			public const int ahRimColor = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int ahRimWidth = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int ahSpinSpeed = 2130771993;
			
			// aapt resource value: 0x7f010013
			public const int ahText = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int ahTextColor = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int ahTextSize = 2130771989;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010012
			public const int circleCrop = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatio = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int imageAspectRatioAdjust = 2130771984;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000a
			public const int calendar_active_month_bg = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int calendar_bg = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int calendar_divider = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int calendar_highlighted_day_bg = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int calendar_inactive_month_bg = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int calendar_selected_day_bg = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int calendar_selected_range_bg = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int calendar_text_active = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int calendar_text_inactive = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int calendar_text_selected = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int calendar_text_selector = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int calendar_text_unselectable = 2131034132;
			
			// aapt resource value: 0x7f050009
			public const int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f050016
			public const int common_signin_btn_text_dark = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int common_signin_btn_text_light = 2131034135;
			
			static Color()
			{
				ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int calendar_day_headers_paddingbottom = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int calendar_month_title_bottommargin = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int calendar_month_topmargin = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int calendar_text_medium = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int calendar_text_small = 2131165188;
			
			static Dimension()
			{
				ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calendar_bg_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_full_open_on_phone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_ic_googleplayservices = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_disabled_focus_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_disabled_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_focus_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_focus_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_normal_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_normal_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_icon_pressed_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_icon_pressed_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_focus_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_disabled_focus_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_disabled_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_focus_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_focus_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_normal_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_normal_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_text_pressed_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_text_pressed_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_errorstatus = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_plusone_medium_off_client = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_plusone_small_off_client = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_plusone_standard_off_client = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_plusone_tall_off_client = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_successstatus = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int icon = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int powered_by_google_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int powered_by_google_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int roundedbg = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int roundedbgdark = 2130837542;
			
			static Drawable()
			{
				ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090005
			public const int adjust_height = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int adjust_width = 2131296262;
			
			// aapt resource value: 0x7f09000f
			public const int calendar_grid = 2131296271;
			
			// aapt resource value: 0x7f090008
			public const int calendar_view = 2131296264;
			
			// aapt resource value: 0x7f090000
			public const int hybrid = 2131296256;
			
			// aapt resource value: 0x7f09000a
			public const int left_arrow = 2131296266;
			
			// aapt resource value: 0x7f09000d
			public const int loadingImage = 2131296269;
			
			// aapt resource value: 0x7f09000b
			public const int loadingProgressBar = 2131296267;
			
			// aapt resource value: 0x7f09000e
			public const int loadingProgressWheel = 2131296270;
			
			// aapt resource value: 0x7f090001
			public const int none = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int normal = 2131296258;
			
			// aapt resource value: 0x7f090009
			public const int right_arrow = 2131296265;
			
			// aapt resource value: 0x7f090003
			public const int satellite = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int terrain = 2131296260;
			
			// aapt resource value: 0x7f09000c
			public const int textViewStatus = 2131296268;
			
			// aapt resource value: 0x7f090007
			public const int title = 2131296263;
			
			static Id()
			{
				ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_pager_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_picker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loading = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int loadingimage = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int loadingprogress = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int month = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int week = 2130903047;
			
			static Layout()
			{
				ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040023
			public const int ApplicationName = 2130968611;
			
			// aapt resource value: 0x7f040022
			public const int Hello = 2130968610;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int common_android_wear_notification_needs_update_text = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int common_android_wear_update_text = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int common_android_wear_update_title = 2130968591;
			
			// aapt resource value: 0x7f04001f
			public const int common_google_play_services_api_unavailable_text = 2130968607;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_enable_button = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_enable_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_enable_title = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_error_notification_requested_by_msg = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_install_button = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_install_text_phone = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_install_text_tablet = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_title = 2130968583;
			
			// aapt resource value: 0x7f040017
			public const int common_google_play_services_invalid_account_text = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_invalid_account_title = 2130968598;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_needs_enabling_title = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_network_error_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_network_error_title = 2130968596;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_needs_update_title = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_notification_ticker = 2130968578;
			
			// aapt resource value: 0x7f040021
			public const int common_google_play_services_sign_in_failed_text = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int common_google_play_services_sign_in_failed_title = 2130968608;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_unknown_issue = 2130968600;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_unsupported_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_unsupported_title = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_update_button = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_update_text = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_update_title = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_updating_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_updating_title = 2130968594;
			
			// aapt resource value: 0x7f04001e
			public const int common_open_on_phone = 2130968606;
			
			// aapt resource value: 0x7f04001c
			public const int common_signin_button_text = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text_long = 2130968605;
			
			// aapt resource value: 0x7f040025
			public const int day_name_format = 2130968613;
			
			// aapt resource value: 0x7f040028
			public const int full_date_format = 2130968616;
			
			// aapt resource value: 0x7f040026
			public const int invalid_date = 2130968614;
			
			// aapt resource value: 0x7f040024
			public const int library_name = 2130968612;
			
			// aapt resource value: 0x7f040027
			public const int month_name_format = 2130968615;
			
			static String()
			{
				ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int CalendarCell = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int CalendarCell_CalendarDate = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int CalendarCell_DayHeader = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int CalendarTitle = 2131230720;
			
			static Style()
			{
				ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] ProgressWheel = new int[] {
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
